import * as os from "node:os";
import * as path from "node:path";
import type { Bucket } from "./config-schema.js";

const home = os.homedir();
const claude = path.join(home, ".claude");

export const DEFAULT_BUCKETS: Record<string, Bucket> = {
	"claude-config": {
		enabled: true,
		paths: [
			path.join(claude, "agents"),
			path.join(claude, "commands"),
			path.join(claude, "hooks"),
			path.join(claude, "rules"),
			path.join(claude, "skills"),
			path.join(claude, "output-styles"),
		],
		ignore: ["*.log", "*.lock", "*.bak-*"],
		versioning: { type: "simple", keep: 10 },
	},
	"claude-conversations": {
		enabled: true,
		paths: [path.join(claude, "projects")],
		ignore: ["*.tmp"],
		versioning: { type: "simple", keep: 5 },
	},
	// Only the durable, portable task lists belong here. `jobs`, `session-env`
	// and `file-history` are machine-local runtime state per Claude Code's own
	// docs (session-env = regenerated by SessionStart hooks; file-history =
	// checkpoint/undo snapshots; jobs = live background-agent state). Syncing them
	// produced the overwhelming majority of conflict files at re-pair time and
	// contributes nothing to resuming a conversation on another machine — the
	// transcript under `claude-conversations` carries all the resume context.
	"claude-agent-state": {
		enabled: true,
		paths: [path.join(claude, "tasks")],
		ignore: ["*.tmp", "*.lock"],
		versioning: { type: "simple", keep: 5 },
	},
	"claude-worktrees": {
		enabled: true,
		paths: [path.join(claude, "worktrees")],
		ignore: [],
		versioning: { type: "simple", keep: 3 },
	},
	"claude-plugins": {
		enabled: false,
		paths: [path.join(claude, "plugins")],
		ignore: ["cache/", "install-counts-cache.json"],
		versioning: { type: "none", keep: 0 },
	},
	"shell-history": {
		enabled: false,
		paths: [],
		ignore: [],
		versioning: { type: "simple", keep: 10 },
	},
	"code-root": {
		enabled: false,
		paths: [],
		ignore: [],
		versioning: { type: "staggered", keep: 30 },
	},
	"active-projects": {
		enabled: false,
		paths: [],
		ignore: [],
		versioning: { type: "staggered", keep: 30 },
	},
};

export function withCodeRootBucket(
	buckets: Record<string, Bucket>,
	localRoot: string,
	relativePaths: string[] = ["."],
): Record<string, Bucket> {
	const current = buckets["code-root"] ?? DEFAULT_BUCKETS["code-root"];
	const paths = relativePaths.map((relativePath) => path.join(localRoot, relativePath));
	return {
		...buckets,
		"code-root": {
			...current,
			enabled: paths.length > 0,
			paths,
		},
	};
}

export function withDefaultBuckets(buckets: Record<string, Bucket>): Record<string, Bucket> {
	return {
		...DEFAULT_BUCKETS,
		...buckets,
	};
}
