import { usesBackslash } from "./ccsyncignore.js";

export const GLOBAL_IGNORE_PATTERNS: string[] = [
	".git/index",
	".git/index.lock",
	".git/HEAD.lock",
	".git/refs/**/*.lock",
	".git/objects/tmp_*",
	".git/MERGE_*",
	".git/FETCH_HEAD",
	".git/ORIG_HEAD",
	"node_modules",
	".next",
	".nuxt",
	".turbo",
	".cache",
	"dist",
	"build",
	"out",
	"target",
	"__pycache__",
	".venv",
	".env.local",
	".DS_Store",
	"Thumbs.db",
	"*.swp",
	"*.swo",
	"*~",
	"*.log",
	".pnpm-store",
	".yarn",
];

export function buildStignore(
	bucketIgnore: string[],
	globalIgnore: string[] = [],
	projectIgnore?: string[],
): string {
	const project = projectIgnore ?? [];
	const escapeHeader = project.length > 0 && usesBackslash(project) ? "#escape=\\\n" : "";

	const sections = [
		"// Generated by ccsync — do not edit manually",
		"",
		"// Global protections",
		...GLOBAL_IGNORE_PATTERNS,
		...globalIgnore,
		"",
		"// Bucket-specific",
		...bucketIgnore,
	];

	if (project.length > 0) {
		sections.push("", "// Project (.ccsyncignore)", ...project);
	}

	sections.push("");
	return escapeHeader + sections.join("\n");
}
