import { usesBackslash } from "./ccsyncignore.js";

export const GLOBAL_IGNORE_PATTERNS: string[] = [
	".git/index",
	".git/index.lock",
	".git/HEAD.lock",
	".git/refs/**/*.lock",
	".git/objects/tmp_*",
	".git/MERGE_*",
	".git/FETCH_HEAD",
	".git/ORIG_HEAD",
	"node_modules",
	".next",
	".nuxt",
	".turbo",
	".cache",
	"dist",
	"build",
	"out",
	"target",
	"__pycache__",
	".venv",
	".env.local",
	".DS_Store",
	"Thumbs.db",
	"*.swp",
	"*.swo",
	"*~",
	"*.log",
	".pnpm-store",
	".yarn",
	// Claude Code high-churn / regenerable state that otherwise becomes a conflict
	// magnet across machines (session picker cache, plugin pointers, lock files).
	"sessions-index.json",
	"*.wakatime",
	"bridge-pointer.json",
	"*.lock",
	// Transient SQLite sidecars: rewritten on every read/write and never
	// meaningful to sync, so they only ever produce conflicts.
	"*.db-shm",
	"*.db-wal",
	"*.db-journal",
];

/**
 * Prefix `(?d)` onto each plain ignore pattern. The `(?d)` flag lets Syncthing
 * delete an otherwise-ignored file when it must remove a directory that was
 * deleted on a peer — without it, a stale lock/tmp/cache file inside a
 * remotely-deleted dir wedges the pull with "directory has been deleted on a
 * remote device but contains ignored files". Negations (`!…`) and patterns that
 * already carry a `(?…)` flag are left untouched.
 */
function deletable(patterns: string[]): string[] {
	return patterns.map((p) => {
		const t = p.trim();
		if (!t || t.startsWith("!") || t.startsWith("(?")) return p;
		return `(?d)${p}`;
	});
}

export function buildStignore(
	bucketIgnore: string[],
	globalIgnore: string[] = [],
	projectIgnore?: string[],
): string {
	const project = projectIgnore ?? [];
	const escapeHeader = project.length > 0 && usesBackslash(project) ? "#escape=\\\n" : "";

	const sections = [
		"// Generated by ccsync — do not edit manually",
		"",
		"// Global protections",
		...deletable(GLOBAL_IGNORE_PATTERNS),
		...deletable(globalIgnore),
		"",
		"// Bucket-specific",
		...deletable(bucketIgnore),
	];

	if (project.length > 0) {
		sections.push("", "// Project (.ccsyncignore)", ...project);
	}

	sections.push("");
	return escapeHeader + sections.join("\n");
}
